--Core KPIs
-------------------------------------
SELECT SUM(SALES_AMOUNT) AS TOTAL_SALES FROM GOLD.FACT_SALES;

SELECT SUM(QUANTITY) AS TOTAL_QUANTITY FROM GOLD.FACT_SALES;

SELECT AVG(PRICE) AS AVG_PRICE FROM GOLD.FACT_SALES;

SELECT COUNT(DISTINCT ORDER_NUMBER) AS TOTAL_ORDERS FROM GOLD.FACT_SALES;
--------------------------------------
--Customers & products KPIs
--------------------------------------
SELECT COUNT(*) AS TOTAL_CUSTOMERS FROM GOLD.DIM_CUSTOMERS;

SELECT COUNT(DISTINCT CUSTOMER_KEY)
FROM GOLD.FACT_SALES;
--------------------------------------
-- Full KPI report
--------------------------------------
SELECT 'TOTAL SALES' AS METRIC, SUM(SALES_AMOUNT) FROM GOLD.FACT_SALES
UNION ALL
SELECT 'TOTAL QUANTITY', SUM(QUANTITY) FROM GOLD.FACT_SALES
UNION ALL
SELECT 'TOTAL ORDERS', COUNT(DISTINCT ORDER_NUMBER) FROM GOLD.FACT_SALES;
