--Core KPIs
-------------------------------------
SELECT SUM(SALES_AMOUNT) AS TOTAL_SALES FROM GOLD.FACT_SALES;

SELECT SUM(QUANTITY) AS TOTAL_QUANTITY FROM GOLD.FACT_SALES;

SELECT AVG(PRICE) AS AVG_PRICE FROM GOLD.FACT_SALES;

SELECT COUNT(DISTINCT ORDER_NUMBER) AS TOTAL_ORDERS FROM GOLD.FACT_SALES;
